### ISSUE TITLE
获取数据失败

### ISSUE THREAD

**Issue by amychanging** [zhaoyiming0803/VueNode#1]

**Comment by zymseo** [comment]
看看数据库连接是否正确，数据是否导入成功。可以发下截图或相关代码。

**Comment by oaichina** [comment]
数据库配置是在哪个文件？

**Comment by zhaixww** [comment]
想知道你们在本地在浏览器是访问什么地址

**Comment by zhaoyiming0803** [comment]
> 数据库配置是在哪个文件？

https://github.com/zhaoyiming0803/VueNode/blob/dev/server/helper/db.js
