### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by Zuojiangtao** [zhaoyiming0803/VueNode#2]
(node:8596) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: spawn cmd ENOENT
(node:8596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zymseo** [comment]
请使用最新版本，前几天已经修复了相关问题！

**Comment by Zuojiangtao** [comment]
没有，还是那样，是不是版本问题，我node8.2.1的版本，npm是5.3.0的版本

**Comment by zymseo** [comment]
可以截个图吗？我看下报错信息。

**Comment by Zuojiangtao** [comment]
![Uploading image.png…]()
![tim 20171220163812](https://user-images.githubusercontent.com/22252182/34198304-dd6cd012-e5a4-11e7-9739-d4e8731b5368.png)

**Comment by Zuojiangtao** [comment]
而且只能手动地打开浏览器，不会自动打开浏览器

**Comment by zymseo** [comment]
安装最新的NodeJs，然后重新下载项目，不会有问题的。

**Comment by Zuojiangtao** [comment]
试了没用的，还是这样

**Comment by think2cat** [comment]
用npm 还是 cnpm
不建议cnpm，会有莫名其妙的问题
还有就是网络问题，我在公司npm也经常下不完整，在家下啥事木有

**Comment by zhaixww** [comment]
想知道你们在本地在浏览器是访问什么地址
