### ISSUE TITLE
修改server/account/login里向前台返回的数据后，数据请求返回的数据为什么还是{backInfo: "1", id: 1, phone: "18582561486"}不变呢？

### ISSUE THREAD

**Issue by Strider20151** [zhaoyiming0803/VueNode#3]
修改server/account/login里向前台返回的数据后，数据请求返回的数据为什么还是{backInfo: "1", id: 1, phone: "18582561486"}不变呢？

第32行的res.json，把phone去掉，但是返回数据里还是有phone，请问是什么原因呢？求解答
res.json({
				backInfo: '1',
				id: data[0].id,
				name: data[0].name,
				phone: phone
			});

**Comment by zymfe** [comment]
后面我抽时间做热更新

**Comment by zhaixww** [comment]
想知道你们在本地在浏览器是访问什么地址

**Comment by zhaoyiming0803** [comment]
> 我找到原因了，每次只有修改后再一次npm run dev才能修改成功，这样好麻烦，请问不能保存后自动运行吗？

可以重新 pull 下代码(https://github.com/zhaoyiming0803/VueNode.git)，直接 npm run start，更改完后端代码，就可以立刻生效了哈。
