### ISSUE TITLE
项目运行之后图片全部都是获取不到的

### ISSUE THREAD

**Issue by SuiKaSan** [zhaoyiming0803/VueNode#4]

**Comment by zymfe** [comment]
图片地址是放在数据库里的，应该是404了，你可以手动更新一下数据库表，换一下url

**Comment by zhaixww** [comment]
想知道你们在本地在浏览器是访问什么地址

**Comment by zhaoyiming0803** [comment]
> 想知道你们在本地在浏览器是访问什么地址

可以看下webpack.dev.config哈，在本地运行的时候，有启动devServer，可以根据devServer配置本地host
