### ISSUE TITLE
后端向前端传递数据

### ISSUE THREAD

**Issue by Judy123LD** [zhaoyiming0803/VueNode#5]
您好，想问一下后端向前端传递json数据具体是哪几个文件？想清楚学习一下这一部分

**Comment by zymfe** [comment]
server目录是nodejs 代码

**Comment by zhaixww** [comment]
想知道你们在本地在浏览器是访问什么地址

**Comment by Judy123LD** [comment]
就是前端运行起来的localhost+端口号啊
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhaixww"<notifications@github.com&gt;; 
发送时间: 2020年6月29日(星期一) 下午3:35
收件人: "zhaoyiming0803/VueNode"<VueNode@noreply.github.com&gt;; 
抄送: "liudi"<1329151432@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhaoyiming0803/VueNode] 后端向前端传递数据 (#5)





 
想知道你们在本地在浏览器是访问什么地址

**Comment by zhaoyiming0803** [comment]
> 您好，想问一下后端向前端传递json数据具体是哪几个文件？想清楚学习一下这一部分

server 目录是所有的后端代码
